# Generated by Django 4.1 on 2023-06-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='tax',
        ),
        migrations.AddField(
            model_name='addcustomer',
            name='address',
            field=models.CharField(default='e', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addcustomer',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('goods', 'goods'), ('service', 'service')], default='goods', max_length=255),
            preserve_default=False,
        ),
    ]
