# Generated by Django 4.1 on 2023-06-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_invoice_delete_package_delete_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcustomer',
            name='mobile',
            field=models.CharField(default='gghj', max_length=255),
            preserve_default=False,
        ),
    ]
