# Generated by Django 4.1 on 2023-06-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_invoice_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance_due',
        ),
    ]
