# Generated by Django 4.1.7 on 2023-07-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_items_tableitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableitems',
            old_name='Invoice_id',
            new_name='Invoice_ids',
        ),
    ]
