# Generated by Django 4.1.7 on 2023-07-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_rename_invoice_id_tableitems_invoice_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableitems',
            old_name='Invoice_ids',
            new_name='invoice',
        ),
    ]
