# Generated by Django 4.1.7 on 2023-07-15 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableitems',
            name='amount',
        ),
    ]
