# Generated by Django 4.1.7 on 2023-07-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_remove_tableitems_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid')], default='draft', max_length=10),
        ),
    ]
