# Generated by Django 4.1.7 on 2023-08-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableitems',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.invoice'),
        ),
    ]
