# Generated by Django 4.1.7 on 2023-08-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_alter_tableitems_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='order_number',
        ),
    ]
