# Generated by Django 6.0.6 on 2026-08-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_remove_invoice_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableitems',
            old_name='quality',
            new_name='quantity',
        ),
    ]
